### ISSUE TITLE
Force minimum width

### ISSUE THREAD

**Issue by MakisH** [precice/run.precice-frontend#9]
When reducing the width of the window, several element start to look ugly (see screenshot).

![narrow](https://user-images.githubusercontent.com/4943683/45813615-5c739480-bcd3-11e8-80a0-e080c0efe76a.png)

I suggest that we enforce some minimum width. This should be the minimum we can afford. With some small adjustments of the progress bar spacing, the "HIDE" button, and the "simulation status", 800px would be feasible. However, this could be different on different screens/browsers.

**Comment by shkodm** [comment]
Problems with Progress bar spacing, hide button should be fixed in f28c2d476129bcf5fb4700f4426a618b525fa384 and 7b2120d04394456d3d9c3e0aa25e29676b501116 correspondingly.
